apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: linting-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/upslopeio/lint-markdown-files
  pipelineRef:
    name: markdown-linting
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
