apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: yaml-linting-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/tekton-pipelines-yaml-remi-serra
  pipelineRef:
    name: yaml-linting
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
